apiVersion: v2
appVersion: "1.4.0"
description: Fineract Engine
name: fin-engine
version: 1.4.0-SNAPSHOT
dependencies:
- name: mariadb
  version: 11.5.0
  repository: "https://charts.bitnami.com/bitnami"
  alias: mysql
  condition: mariadb.enabled, mysql.enabled

