apiVersion: v1
appVersion: "1.0"
description: Fineract Engine
name: fin-engine
version: 1.0.0-SNAPSHOT
dependencies:
- name: fin-engine
  version: 1.0.0-SNAPSHOT
  repository: https://fynarfin.io/images/fineract

