fineract:
  enabled: true
  db: fineract-mysql
  DFSPIDS: ""
  SPRING_PROFILES_ACTIVE: "bb"
  image: "docker.io/openmf/fineract:1.9.0"
  spec: 
    template:
       spec:
         containers:
            env:
              FINERACT_DEFAULT_TENANTDB_IDENTIFIER: "default"
              FINERACT_DEFAULT_TENANTDB_NAME: "fineract_default"
              FINERACT_DEFAULT_TENANTDB_HOSTNAME: "fineract-mysql"
              FINERACT_DEFAULT_TENANTDB_PORT: "3306"
              FINERACT_HIKARI_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
              FINERACT_HIKARI_JDBC_URL: jdbc:mariadb://fineract-mysql:3306/fineract_tenants
              FINERACT_SERVER_PORT: 8443
  preStopScript: 'echo -e "******Fineract is stopping********";'
  ingress:
    enabled: true
    hostname: "fynams1.sandbox.fynarfin.io"
    path: "/"
    wildcardhostname: "*.sandbox.fynarfin.io"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"  
  resources:
    limits:
      cpu: "1000m"
      memory: "2Gi"
    requests:
      cpu: "200m"
      memory: "0.5Gi"
  deployment:
    extraEnvs:
      - name: "FINERACT_SECURITY_BASICAUTH_ENABLED"
        value: 'true'
      - name: "FINERACT_SECURITY_OAUTH_ENABLED"
        value: 'false'

communityapp:
  enabled: false
  lookforservice: true
  image: "docker.io/openmf/community-app:latest"
  ingress:
    enabled: false
    hostname: "communityapp.sandbox.fynarfin.io"
    path: "/"
    wildcardhostname: "communityapp.sandbox.fynarfin.io"
    annotations:
      kubernetes.io/ingress.class: "nginx"
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "0.5Gi"

webapp:
  enabled: true
  image: "docker.io/openmf/web-app:master"
  ingress:
    enabled: true
    hostname: "web-app1.sandbox.fynarfin.io"
    path: "/"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "0.5Gi" 

selfservice:
  image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/fineract/phee-ns/web-self-service-app:latest"
  ingress:
    enabled: false
    hostname: ""
    path: "/self"
    annotations: {}

mysql:
  fullnameOverride: fineract-mysql
  enabled: false
  image:
    tag: "10.5.16-debian-11-r22"
    debug: true
  auth:
    username: "mifos"
    password: "password"
    rootPassword: "4ET6ywqlGt"
  initdbScripts:
    setup.sql: |-
      # create databases
      CREATE DATABASE IF NOT EXISTS `fineract_tenants`;
      CREATE DATABASE IF NOT EXISTS `fineract_default`;
      # create root user and grant rights
      GRANT ALL ON *.* TO 'root'@'%';
      GRANT ALL PRIVILEGES ON `fineract_tenants`.* TO 'mifos';
      GRANT ALL PRIVILEGES ON `fineract_default`.* TO 'mifos';
  primary:
    resources:
      requests:
        memory: "0.5Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"

wildcardhostname: "*.sandbox.fynarfin.io"

tls: ""

post_installation_job:
  enabled: true
  tenants: "gorilla,rhino,lion,wakanda,jupiter,venus,pluto"
