fin-engine:
  fineract:
    DFSPIDS: "rhino,gorilla"
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/fineract:mysqllatest"
    spec: 
      template:
        spec:
          containers:
            env:
              FINERACT_DEFAULT_TENANTDB_IDENTIFIER: "rhino"
              FINERACT_DEFAULT_TENANTDB_NAME: "rhino"
    postStartScript: 'echo -e "******Fineract is Started successfully********"; mysql -h fineract-mysql -uroot -p4ET6ywqlGt fineract_tenants -e  INSERT INTO \`tenant_server_connections\` (\`id\`, \`schema_server\`, \`schema_name\`, \`schema_server_port\`, \`schema_username\`, \`schema_password\`, \`auto_update\`, \`pool_initial_size\`, \`pool_validation_interval\`, \`pool_remove_abandoned\`, \`pool_remove_abandoned_timeout\`, \`pool_log_abandoned\`, \`pool_abandon_when_percentage_full\`, \`pool_test_on_borrow\`, \`pool_max_active\`, \`pool_min_idle\`, \`pool_max_idle\`, \`pool_suspect_timeout\`, \`pool_time_between_eviction_runs_millis\`, \`pool_min_evictable_idle_time_millis\`, \`schema_connection_parameters\`, \`readonly_schema_server\`, \`readonly_schema_name\`, \`readonly_schema_server_port\`, \`readonly_schema_username\`, \`readonly_schema_password\`, \`readonly_schema_connection_parameters\`) VALUES (2, \'fineract-mysql\', \'gorilla\', \'3306\', \'mifos\', \'password\', 1, 5, 30000, 1, 60, 1, 50, 1, 40, 20, 10, 60, 34000, 60000, \'serverTimezone=UTC&useLegacyDatetimeCode=false&sessionVariables=time_zone=\\\'-00:00\\\'\', NULL, NULL, NULL, NULL, NULL, NULL); mysql -h fineract-mysql -uroot -p4ET6ywqlGt fineract_tenants -e INSERT INTO \`tenants\` (\`id\`, \`identifier\`, \`name\`, \`timezone_id\`, \`country_id\`, \`joined_date\`, \`created_date\`, \`lastmodified_date\`, \`oltp_id\`, \`report_id\`) VALUES (2, \'gorilla\', \'test2\', \'Asia/Kolkata\', NULL, NULL, NULL, NULL, 2, 2);";'
    ingress:
      enabled: true
      hostname: "rhino.mifos.g2pconnect.io"
      wildcardhostname: "rhino.mifos.g2pconnect.io"
      
    resources:
      limits:
        cpu: "1000m"
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "0.5Gi"     

  communityapp:
    enabled: true
    ingress:
      enabled: true
      hostname: "communityapp.mifos.g2pconnect.io"
      wildcardhostname: "communityapp.mifos.g2pconnect.io"

  webapp:
    ingress:
      enabled: false
      hostname: "webapp.mifos.g2pconnect.io"
      
  mariadb:
    fullnameOverride: fineract-mysql
    auth:
      username: "mifos"
      password: "password"
      rootPassword: "4ET6ywqlGt"
    initdbScripts:
      setup.sql: |-
        # create databases
        CREATE DATABASE IF NOT EXISTS `fineract_tenants`;
        CREATE DATABASE IF NOT EXISTS `gorilla`;
        CREATE DATABASE IF NOT EXISTS `rhino`;
        # create root user and grant rights
        GRANT ALL ON *.* TO 'root'@'%';
        GRANT ALL PRIVILEGES ON `fineract_tenants`.* TO 'mifos';
        GRANT ALL PRIVILEGES ON `gorilla`.* TO 'mifos';
        GRANT ALL PRIVILEGES ON `rhino`.* TO 'mifos';
         
        
    primary:
      resources:
        requests:
          memory: "0.5Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1000m"    
   
