fin-engine:
  fineract:
    DFSPIDS: "rhino,gorilla"
    spec: 
      template:
        spec:
          containers:
            env:
              FINERACT_DEFAULT_TENANTDB_IDENTIFIER: "rhino"
              FINERACT_DEFAULT_TENANTDB_NAME: "rhino"
    ingress:
      enabled: true
      hostname: "rhino.mifos.g2pconnect.io"
      wildcardhostname: "rhino.mifos.g2pconnect.io"
    resources:
      limits:
        cpu: "1000m"
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "0.5Gi"     

  communityapp:
    enabled: true
    ingress:
      enabled: true
      hostname: "communityapp.mifos.g2pconnect.io"
      wildcardhostname: "communityapp.mifos.g2pconnect.io"

  webapp:
    ingress:
      enabled: false
      hostname: "webapp.mifos.g2pconnect.io"
  mariadb:
    fullnameOverride: fineract-mysql
    auth:
      username: "mifos"
      password: "password"
      rootPassword: "4ET6ywqlGt"
    initdbScripts:
      setup.sh: |-
        #!/bin/sh 
        # curl -O fineract_tenants_backup.sql "https://fynarfin.io/images/fineract/fineract_tenants_backup.sql";
        # mysql -P 3306 -u root -p4ET6ywqlGt < "fineract_tenants_backup.sql"
         
        
    primary:
      resources:
        requests:
          memory: "0.5Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1000m"    
   
