apiVersion: v1
kind: Service
metadata:
  name: self-service
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  selector:
    app: self-service
  type: NodePort

---
{{- if .Values.selfservice.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selfservice
  annotations:
{{- if .Values.selfservice.ingress.annotations }}
{{ toYaml .Values.selfservice.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.selfservice.ingress.hostname }}"
      http:
        paths:
          - path: "{{ .Values.selfservice.ingress.path }}"
            pathType: Prefix
            backend:
              service:
                name: selfservice
                port: 
                  number: 80
  tls:
    - hosts:
        - "{{ .Values.wildcardhostname }}"
      secretName: "{{ .Values.tls }}"
{{- end }}