{{- if .Values.webapp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: "{{ .Values.namespace }}"
  labels:
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:      
      - image: "{{ .Values.webapp.image }}"
        resources:
          limits:
            cpu: "{{ .Values.webapp.resources.limits.cpu }}"
            memory: "{{ .Values.webapp.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.webapp.resources.requests.cpu }}"
            memory: "{{ .Values.webapp.resources.requests.memory }}"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 90
          periodSeconds: 1                      
        imagePullPolicy: Always
        name: web-app-container
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
#      serviceAccountName: ""
#      volumes: null
{{- end }}